# generic chunk structure
CHUNK_TAG_SIZE = 4
CHUNK_SUB_TAG_SIZE = 4
# only includes the chunk data without the pre-data members
# to retrieve the total chunk size we do
# CHUNK_DATA_SIZE + 8 (chunk_data_size size member) + 4 (subtag) + 4 (tag)
CHUNK_DATA_SIZE_SIZE = 8

###########################################
# data structure for specific chunk types #
###########################################

# the offset is relative to the start of the catalog uuid section, hence,
# the size of the catalog uuid array is CATALOG_CHUNK_SUBSYSTEM_STRINGS_OFF // 16 (uuid size)
CATALOG_CHUNK_SUBSYSTEM_STRINGS_OFF_UUID_REL = 16
CATALOG_CHUNK_SUBSYSTEM_STRINGS_SIZE = 2
CATALOG_CHUNK_PROCESS_INFO_OFF_UUID_REL = 18
CATALOG_CHUNK_PROCESS_INFO_SIZE = 2
CATALOG_CHUNK_NUMBER_OF_PROCESS_INFO_OFF = 20
CATALOG_CHUNK_NUMBER_OF_PROCESS_INFO_SIZE = 2
CATALOG_CHUNK_SUB_CHUNK_OFF_UUID_REL = 22
CATALOG_CHUNK_SUB_CHUNK_OFF_SIZE = 2
CATALOG_CHUNK_SUB_CHUNK_NUMBER_OFF_UUID_REL = 24
CATALOG_CHUNK_SUB_CHUNK_NUMBER_SIZE = 2
CATALOG_CHUNK_SUB_CHUNK_PADDING_SIZE = 6
CATALOG_CHUNK_EARLIEST_FIREHOSE_TIMESTAMP_SIZE = 8
CATALOG_CHUNK_UUID_SIZE = 16
# CATALOG_CHUNK_UUID_ARRAY_SIZE is calculated using the value of CATALOG_CHUNK_SUBSYSTEM_STRINGS_OFF_UUID_REL

# PROC INFO

CATALOG_CHUNK_PROC_ENTRY_INDEX_SIZE = 2
CATALOG_CHUNK_PROC_ENTRY_FLAGS_MEMBER_SIZE = 2
CATALOG_CHUNK_PROC_ENTRY_1ST_UNKNOWN_MEMBER_SIZE = 4
CATALOG_CHUNK_PROC_ENTRY_2ND_UNKNOWN_MEMBER_SIZE = 4
CATALOG_CHUNK_PROC_ENTRY_3RD_UNKNOWN_MEMBER_SIZE = 4
CATALOG_CHUNK_PROC_ENTRY_4TH_UNKNOWN_MEMBER_SIZE = 2
CATALOG_CHUNK_PROC_ENTRY_PROC_UUID_INDEX_SIZE = 2
CATALOG_CHUNK_PROC_ENTRY_DSC_UUID_INDEX_SIZE = 2
CATALOG_CHUNK_PROC_ENTRY_PROC_ID_1ST_SIZE = 8
CATALOG_CHUNK_PROC_ENTRY_PROC_ID_2ND_SIZE = 4
CATALOG_CHUNK_PROC_ENTRY_PROC_PID_SIZE = 4
CATALOG_CHUNK_PROC_ENTRY_PROC_EUID_SIZE = 4
# CATALOG_CHUNK_PROC_ENTRY_UUID_INFO_SIZE = 16 * CATALOG_CHUNK_PROC_ENTRY_UUID_NUM_SIZE
CATALOG_CHUNK_PROC_ENTRY_UUID_NUM_SIZE = 4

# CATALOG_CHUNK_PROC_ENTRY_SUBSYSTEMS_INFO_SIZE = 6 * CATALOG_CHUNK_PROC_ENTRY_NUMBER_OF_SUBSYSTEMS_SIZE
CATALOG_CHUNK_PROC_ENTRY_NUMBER_OF_SUBSYSTEMS_SIZE = 4
CATALOG_CHUNK_PROC_ENTRY_SUBSYSTEM_ID_SIZE = 2
CATALOG_CHUNK_PROC_ENTRY_SUBSYSTEM_OFFSET_SIZE = 2
CATALOG_CHUNK_PROC_ENTRY_CATEGORY_OFFSET_SIZE = 2
CATALOG_CHUNK_PROC_ENTRY_UUID_INFO_SIZE_SIZE = 4
CATALOG_CHUNK_PROC_ENTRY_UUID_INFO_UNKNOWN_MEMBER_SIZE = 4
CATALOG_CHUNK_PROC_ENTRY_UUID_INFO_INDEX_SIZE = 2
CATALOG_CHUNK_PROC_ENTRY_UUID_INFO_LOAD_ADDR_LOWER_SIZE = 4
CATALOG_CHUNK_PROC_ENTRY_UUID_INFO_LOAD_ADDR_UPPER_SIZE = 2

# CATALOG SUB CHUNK
CATALOG_CHUNK_SUB_CHUNK_START_TIME_SIZE = 8
CATALOG_CHUNK_SUB_CHUNK_END_TIME_SIZE = 8
CATALOG_CHUNK_SUB_CHUNK_UNCOMPRESSED_DATA_SIZE_SIZE = 4
CATALOG_CHUNK_SUB_CHUNK_ALGO_SIZE = 4
CATALOG_CHUNK_SUB_CHUNK_PROC_NUM_SIZE = 4
CATALOG_CHUNK_SUB_CHUNK_PROC_INDEX_SIZE = 2
CATALOG_CHUNK_SUB_CHUNK_NUM_OF_STRINGS_SIZE = 4
CATALOG_CHUNK_SUB_CHUNK_STRING_OFFSET_SIZE = 2

# CHUNK SET CHUNK

CHUNK_SET_START_MAGIC_COMPRESSED = b'bv41'
CHUNK_SET_START_MAGIC_DECOMPRESSED = b'bv4-'
CHUNK_SET_END_MAGIC = b'bv4$'
CHUNK_SET_LZ4_START_MAGIC_SIZE = 4
CHUNK_SET_LZ4_END_MAGIC_SIZE = 4
CHUNK_SET_LZ4_COMPRESSED_DATA_SIZE = 4
CHUNK_SET_LZ4_DECOMPRESSED_DATA_SIZE = 4

# SIMPLE DUMP CHUNK

SIMPLE_DUMP_CHUNK_TTL_SIZE = 1
SIMPLE_DUMP_CHUNK_LOG_TYPE_SIZE = 1
SIMPLE_DUMP_CHUNK_UNKNOWN_1ST_SIZE = 2
SIMPLE_DUMP_CHUNK_TIMESTAMP_SIZE = 8
SIMPLE_DUMP_CHUNK_THREAD_ID_SIZE = 8
SIMPLE_DUMP_CHUNK_LOAD_ADDR_SIZE = 8
SIMPLE_DUMP_CHUNK_SENDER_UUID_SIZE = 16
SIMPLE_DUMP_CHUNK_DSC_STRINGS_UUID = 16
SIMPLE_DUMP_CHUNK_UNKNOWN_2ND_SIZE = 4
SIMPLE_DUMP_CHUNK_SUBSYSTEM_STRING_SIZE_SIZE = 4
SIMPLE_DUMP_CHUNK_MESSAGE_STRING_SIZE_SIZE = 4

# FIREHOSE CHUNK

FIREHOSE_CHUNK_TTL_SIZE = 1
FIREHOSE_CHUNK_COLLAPSED_SIZE = 1
FIREHOSE_CHUNK_UNKNOWN_1ST_SIZE = 2
FIREHOSE_CHUNK_PUBLIC_DATA_SIZE = 2
FIREHOSE_CHUNK_PRIVATE_DATA_VIRTUAL_OFFSET_SIZE = 2
FIREHOSE_CHUNK_UNKNOWN_2ND_SIZE = 2
FIREHOSE_CHUNK_STREAM_TYPE_SIZE = 1
FIREHOSE_CHUNK_UNKNOWN_3RD_SIZE = 1
FIREHOSE_CHUNK_BASE_CONTINUOUS_TIME_SIZE = 8

# FIREHOSE TRACE POINT

FIREHOSE_TRACE_POINT_RECORD_TYPE_SIZE = 1
FIREHOSE_TRACE_POINT_LOG_TYPE_SIZE = 1
FIREHOSE_TRACE_POINT_FLAGS_TYPE_SIZE = 2
FIREHOSE_TRACE_POINT_FORMAT_STRING_REFERENCE_SIZE = 4
FIREHOSE_TRACE_POINT_TID_SIZE = 8
FIREHOSE_TRACE_POINT_CONTINUOUS_TIME_DELTA_SIZE = 6
FIREHOSE_TRACE_POINT_DATA_SIZE = 2
FIREHOSE_TRACE_POINT_DATA_ITEM_VALUE_TYPE_SIZE = 1
FIREHOSE_TRACE_POINT_DATA_ITEM_DATA_SIZE = 1
FIREHOSE_TRACE_POINT_DATA_ITEM_VALUE_DATA_OFFSET_SIZE = 2
FIREHOSE_TRACE_POINT_DATA_ITEM_VALUE_DATA_SIZE_SIZE = 2

# FIREHOSE LOG TRACE POINT

FIREHOSE_TRACE_POINT_LOG_ACTIVITY_ID_SIZE = 8
FIREHOSE_TRACE_POINT_LOG_PRIVATE_DATA_RANGE_SIZE = 4
FIREHOSE_TRACE_POINT_LOG_UUID_ENTRY_LOAD_ADDRESS_LOWER_SIZE = 4
FIREHOSE_TRACE_POINT_LOG_LARGE_OFFSET_DATA_SIZE = 2
FIREHOSE_TRACE_POINT_LOG_UUID_ENTRY_LOAD_ADDRESS_UPPER_SIZE = 2
FIREHOSE_TRACE_POINT_LOG_UUID_SIZE = 16
FIREHOSE_TRACE_POINT_LOG_LARGE_SHARED_CACHE_DATA_SIZE = 2
FIREHOSE_TRACE_POINT_LOG_SUBSYSTEM_ID_SIZE = 2
FIREHOSE_TRACE_POINT_LOG_TTL_SIZE = 1
FIREHOSE_TRACE_POINT_LOG_OVERSIZE_DATA_REFERENCE_SIZE = 2
FIREHOSE_TRACE_POINT_LOG_UNKNOWN_SIZE = 1
FIREHOSE_TRACE_POINT_LOG_NUM_OF_DATA_ITEMS_SIZE = 1
FIREHOSE_TRACE_POINT_LOG_BACKTRACE_UNKNOWN_1ST_SIZE = 2
FIREHOSE_TRACE_POINT_LOG_BACKTRACE_UNKNOWN_2ND_SIZE = 1
FIREHOSE_TRACE_POINT_LOG_BACKTRACE_NUMBER_OF_IMAGES_SIZE = 1
FIREHOSE_TRACE_POINT_LOG_BACKTRACE_NUMBER_OF_FRAMES_SIZE = 1
FIREHOSE_TRACE_POINT_LOG_BACKTRACE_UNKNOWN_3RD_SIZE = 1

############################################################################

ABSOLUTE_FILE_TYPE = "absolute"
MAIN_EXE_FILE_TYPE = "main_exe"
SHARED_CACHE_FILE_TYPE = "dsc"
UUID_RELATIVE_FILE_TYPE = "uuid_relative"
LARGE_SHARED_CACHE_FILE_TYPE = "large_dsc"

FIREHOSE_TRACE_POINT_FLAG_HAS_CURRENT_AID = "has_current_aid"
FIREHOSE_TRACE_POINT_FLAG_STRING_FILE_TYPE = "strings_file_type"
FIREHOSE_TRACE_POINT_FLAG_HAS_UNIQUE_PID = "has_unique_pid"
FIREHOSE_TRACE_POINT_FLAG_HAS_LARGE_OFFSET = "has_large_offset"
FIREHOSE_TRACE_POINT_FLAG_HAS_PRIVATE_DATA = "has_private_data"
FIREHOSE_TRACE_POINT_FLAG_HAS_SUBSYSTEM = "has_subsystem"
FIREHOSE_TRACE_POINT_FLAG_HAS_RULES = "has_rules"
FIREHOSE_TRACE_POINT_FLAG_HAS_OVERSIZE = "has_oversize"
FIREHOSE_TRACE_POINT_FLAG_HAS_BACKTRACE = "has_backtrace"
FIREHOSE_TRACE_POINT_FLAG_HAS_NAME_REF = "has_name"
FIREHOSE_TRACE_POINT_FLAG_HAS_OTHER_AID = "has_other_aid"


firehose_trace_point_strings_file_types = {0x0002: MAIN_EXE_FILE_TYPE, 0x0004: SHARED_CACHE_FILE_TYPE,
                                           0x0008: ABSOLUTE_FILE_TYPE, 0x000a: UUID_RELATIVE_FILE_TYPE,
                                           0x000c: LARGE_SHARED_CACHE_FILE_TYPE}

firehose_trace_point_flags = {FIREHOSE_TRACE_POINT_FLAG_HAS_CURRENT_AID: 0x001,
                              FIREHOSE_TRACE_POINT_FLAG_STRING_FILE_TYPE: 0x000e,
                              FIREHOSE_TRACE_POINT_FLAG_HAS_UNIQUE_PID: 0x0010,
                              FIREHOSE_TRACE_POINT_FLAG_HAS_LARGE_OFFSET: 0x0020,
                              FIREHOSE_TRACE_POINT_FLAG_HAS_PRIVATE_DATA: 0x0100,
                              FIREHOSE_TRACE_POINT_FLAG_HAS_SUBSYSTEM: 0x0200,
                              FIREHOSE_TRACE_POINT_FLAG_HAS_RULES: 0x0400,
                              FIREHOSE_TRACE_POINT_FLAG_HAS_OVERSIZE: 0x0800,
                              FIREHOSE_TRACE_POINT_FLAG_HAS_BACKTRACE: 0x1000,
                              FIREHOSE_TRACE_POINT_FLAG_HAS_NAME_REF: 0x8000,
                              FIREHOSE_TRACE_POINT_FLAG_HAS_OTHER_AID: 0x0200}

FIREHOSE_TRACE_POINT_VALUE_TYPE_STRING_RANGE = (0x20, 0x22, 0x40, 0x42)
FIREHOSE_TRACE_POINT_VALUE_TYPE_BINARY_RANGE = (0x30, 0x32, 0xf2)
FIREHOSE_TRACE_POINT_VALUE_TYPE_PRIVATE_RANGE = (0x41,)
FIREHOSE_TRACE_POINT_VALUE_TYPE_32_BIT_PRIVATE = (0x01, 0x21, 0x31)
FIREHOSE_TRACE_POINT_VALUE_TYPE_INT_OR_FLOAT = (0x00, 0x02)
FIREHOSE_TRACE_POINT_VALUE_TYPE_INT_FORMAT_PRECISION = (0x10,)
FIREHOSE_TRACE_POINT_VALUE_TYPE_STRING_FORMAT_PRECISION = (0x12,)
FIREHOSE_TRACE_POINT_VALUE_TYPE_SENSITIVE = (0x25,)

FIREHOSE_TRACE_POINT_STRUCT_STRINGS_BY_SIZE = {1: "<B", 2: "<H", 4: "<I", 8: "<Q"}

FIREHOSE_BINARY_VALUE_DATA_RANGE_TYPE = "bin"
FIREHOSE_STRING_VALUE_DATA_RANGE_TYPE = "str"
FIREHOSE_PRIVATE_VALUE_DATA_RANGE_TYPE = "private"

firehose_trace_point_record_types = {0x00: "Unused", 0x02: "Activity", 0x03: "Trace", 0x04: "Log", 0x06: "Signpost",
                                     0x07: "Loss"}

stream_types = {0x00: "Persist", 0x01: "Special Handling", 0x02: "Memory", 0x03: "Signpost"}

LOG_TYPE_USER_ACTION = "user_action"

log_types = {0x00: "default", 0x01: "info", 0x02: "debug", 0x03: LOG_TYPE_USER_ACTION, 0x10: "error", 0x11: "fault",
             0x40: "Thread Signpost Event", 0x41: "Thread Signpost Start", 0x42: "Thread Signpost End",
             0x80: "Process Signpost Event", 0x81: "Process Signpost start", 0x82: "Process Signpost end",
             0xc0: "System Signpost Event", 0xc1: "System Signpost start", 0xc2: "System Signpost end"}

chunk_types = {0x1000: "Header", 0x6001: "Firehose", 0x6002: "Oversize", 0x6003: "StateDump",
               0x6004: "SimpleDump", 0x600b: "Catalog", 0x600d: "ChunkSet"}
